apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

patches:
- target:
    kind: Service
    name: kargo-demo-service
  patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 30109
images:
- name: docker.artifacts.rbi.tech/nginx/nginx
  newTag: 1.25.4
