apiVersion: v1
kind: ConfigMap
metadata:
  name: kargo-demo-content
data:
  index.html: |-
    <!DOCTYPE html>
    <html>
    <head>
    <title>sit105</title>
    </head>
    <body>

    <h1>sit105</h1>

    </body>
    </html>