apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- configmap.yaml

patches:
- patch: |-
    - op: replace
      path: /spec/ports/0/nodePort
      value: 40000
  target:
    kind: Service
    name: kargo-demo
images:
- name: docker.artifacts.rbi.tech/nginx/nginx
  newTag: 1.25.4
